#Ansible playbook for destroying an AWS resource

# This playbook runs a basic DF command.

- hosts: localhost
  #remote_user: root

  tasks:
      
  - name: run the script
    register: final_result #to store the output of terraform
    terraform: 
     project_path: '/home/cloud_user/'
     state: absent # the state of the resource to be created, absent means destroy it and start it 
     backend_config: #backend configuration to store the state file of terraform 
       bucket: "testmic1234"
       key: "terraform.tfstate2"
       region: "us-west-2"
     variables:
      aws_region: "{{ aws_region }}"      # this will be passed while calling the ansible play-book
      nameTag: "{{ nameTag }}" #this will be passed while calling the ansible play-book

  - debug:
          var:  final_result.outputs.instance_ip_addr.value #the outputs to be defined 
